# RSA keys
jwt:
    rsa-private-key: classpath:certs/privateKey.pem
    rsa-public-key: classpath:certs/publicKey.pem

# DB credentials
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/pet___auth-service
        username: root
        password: ""
        driver-class-name: com.mysql.jdbc.Driver

    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update